### ISSUE TITLE
Problem with running the demo tako80.net in Chromium under Linux Mint

### ISSUE THREAD

**Issue by RealTJ** [pistacchio/tako80#1]
Hi, 
i tried your demo on http://tako80.net/ and it does not run in Chromium. 

The error:
```
tako80.min.js:1 Uncaught TypeError: Cannot read property 'VERTEX_SHADER' of null
    at z (tako80.min.js:1)
    at Object.te [as createProgramInfo] (tako80.min.js:1)
    at init (tako80.min.js:1)
    at run (tako80.min.js:1)
    at FileReader.fileReader.onload (tako80.min.js:1)
```

I have this problem only witg Chromium (Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 17.3 (64-bit)), but not with Firefox (Firefox 54.0 (64-Bit)).

**Comment by pistacchio** [comment]
Hi GoldenIron , thanks for your report.

tako80 has been tested with:
Node 8.0+;
Google Chrome 60+;
Firefox 54+;
Safari 10.1+;
Chromium 61+;

Can you upgrade to the latest version of Chromium? Also, from the error posted, it seems to me a problem with webgl. Is webgl enabled on your installation? You can check it visiting this page with Chromium: chrome://gpu/

Thanks

**Comment by RealTJ** [comment]
Thanks for the info, didn't know that. WebGL and WebGL2 are both "unavailable", i think that is the issue here. Interesting enough it is available in my Firefox, since it works there, but it seems to be an issue with my machine.

As a reference i tried it with Google Chrome Version 59.0.3071.104 on Windows 10 and it worked correctly.

**Comment by pistacchio** [comment]
Oh, so that's the problem! Thanks for reporting your problem and for the further testing in your environment, by the way :)
