### ISSUE TITLE
A Few More Things...

### ISSUE THREAD

**Issue by ZYOUNG10** [pistacchio/tako80#3]
So, I decided to get started with the classic "Hello world!" that you should strat with when using a new program, but, unfortunately I've gone wrong already! 

function init() {

}

function update() {
    layer();
    cls();
    print("hello world!", 100, 100);
    draw();
}

Is my current code, but nothing seems to happen! I have reloaded and compiled multiple times to see what I could do to make it work, and nothing appears to show up. Am I doing something wrong already? I haven't ever really used JS so it's pretty probable I am doing something wrong.

Another thing, it would be nice if you could allow other sign in option other than twitter. Twitter is nice and all, but I've never used it and don't really plan to anytime in the near future. This is just a personal preference as I try to stay off of and out of social media as much as possible. However, even a google+ login system would be more preferable. 

Thanks for the help :D

P.S. This is Zayach on discord ;)

**Comment by Viza74** [comment]
Have you tried reloading the page without cache? 
Shift+Ctrl(or Cmd)+r or Shift+click on the reload button in Chrome.

**Comment by pistacchio** [comment]
We discussed the problem on Discord, it was something weird with the installation :)
